
sampling_method: dopri5
num_sampling_steps: 250
atol: 1e-6
rtol: 1e-3
reverse: false
likelihood: false


#    group.add_argument("--sampling-method", type=str, default="dopri5", help="blackbox ODE solver methods; for full list check https://github.com/rtqichen/torchdiffeq")
#    group.add_argument("--atol", type=float, default=1e-6, help="Absolute tolerance")
#    group.add_argument("--rtol", type=float, default=1e-3, help="Relative tolerance")
#    group.add_argument("--reverse", action="store_true")
#    group.add_argument("--likelihood", action="store_true")