

sampling_method: Euler
num_sampling_steps: 250
diffusion_form: sigma
diffusion_norm: 1.0
last_step: Mean
last_step_size: 0.04



#group.add_argument("--sampling-method", type=str, default="Euler", choices=["Euler", "Heun"])
#    group.add_argument("--diffusion-form", type=str, default="sigma", \
#                        choices=["constant", "SBDM", "sigma", "linear", "decreasing", "increasing-decreasing"],\
#                        help="form of diffusion coefficient in the SDE")
#    group.add_argument("--diffusion-norm", type=float, default=1.0)
#    group.add_argument("--last-step", type=none_or_str, default="Mean", choices=[None, "Mean", "Tweedie", "Euler"],\
#                        help="form of last step taken in the SDE")
#    group.add_argument("--last-step-size", type=float, default=0.04, \
#                        help="size of the last step taken")